BMD-10668 update hapi-bpc
BerlingskeMedia/bpc_console pull request #102
Opened 2021-10-21 13:05 UTC by bmxmaza

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-10668

### Pre/Post release actions:
(none)

2021-10-21 13:09 UTC, dgolabek-sii submitted a review, later dismissed

2021-10-22 04:46 UTC, bmxpapa requested changes

2021-10-22 04:46 UTC, bmxpapa commented on Dockerfile.dev
> +COPY . /build
this change will slow down the builds, whenever something will be changed in the code the layer with installed node dops will be invalidated so npm install will be executed unnecessarily

2021-10-22 04:46 UTC, bmxpapa commented on package.json
> +    "tslib": "^2.3.1",
is this necessary? there is no typescript in that project

2021-11-09 13:10 UTC, bmxpiku submitted a review, later dismissed

2021-11-15 09:23 UTC, bmxpiku submitted a review, later dismissed

2021-11-26 11:39 UTC, bmxpiku commented on package.json
> +    "har-validator": "^5.1.5",
I added this https://github.com/cypress-io/cypress/issues/8265 because its a requirement for cypress installation not to fail...

2021-11-26 12:02 UTC, bmxpapa approved these changes

2021-12-08 09:47 UTC, bmxalgo approved these changes

2021-12-08 09:47 UTC, merged