BMD-6423: ip access per brand
BerlingskeMedia/bpc_console pull request #118
Opened 2021-12-06 11:32 UTC by bmxpapa

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-6423

### Pre/Post release actions:
(none)

2021-12-07 09:10 UTC, bmxpiku approved these changes

2021-12-14 11:27 UTC, bmxpiku submitted a review, later dismissed

2021-12-15 06:36 UTC, dgolabek-sii requested changes

2021-12-15 06:36 UTC, dgolabek-sii commented on README.md
> +docker-compose -f docker-compose.yaml up --build
doesn't docker-compose read that file as default? why to pass it as a parameter? :thinking:

2021-12-15 06:51 UTC, dgolabek-sii approved these changes

2021-12-15 06:59 UTC, merged