BMD-12079 payments fix + refactor
BerlingskeMedia/bpc_console pull request #126
Opened 2021-12-17 07:29 UTC by bmx-makostecka

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-12079

### Pre/Post release actions:
(none)

2021-12-17 12:00 UTC, bmxkrbu requested changes

2021-12-17 12:00 UTC, bmxkrbu commented on client/src/client/pm/sdk.ts
> +const isAccessAdmin = (): boolean => {
```suggestion
const hasAdminAccess = (): boolean => {
```
Perhaps?

2021-12-17 12:27 UTC, bmx-makostecka commented on client/src/client/pm/sdk.ts
> +const isAccessAdmin = (): boolean => {
corrected

2021-12-20 08:34 UTC, bmxkrbu approved these changes

2022-01-03 09:04 UTC, merged