BMD-12682 add email mask
BerlingskeMedia/bpc_console pull request #150
Opened 2022-02-16 13:27 UTC by bmx-makostecka

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-12682

### Pre/Post release actions:
(none)

2022-02-17 14:12 UTC, bmxkrbu requested changes

2022-02-17 14:12 UTC, bmxkrbu commented on client/src/companiesES/Company/EmailMasks/AddEmailMask.tsx
> +  const onClickAddEmailMask = () => {
```suggestion
  const onAddEmailMaskClick = () => {
```
Sounds more accurate 🤠

2022-02-17 14:19 UTC, bmxsele approved these changes

2022-02-18 07:06 UTC, bmxkrbu approved these changes

2022-02-18 07:19 UTC, merged