BMD-6702 - Input moved out of folded lists
BerlingskeMedia/bpc_console pull request #180
Opened 2022-04-08 09:27 UTC by bmxjusu

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-6702
### Pre/Post release actions:
(none)

2022-04-08 09:59 UTC, bmxsele requested changes

2022-04-08 09:59 UTC, bmxsele commented on client/src/components/ArrayItems.tsx
> +    console.log(props.data);
You forgot about this console.log probably :smile: It shouldn't stay in the code, I'd suggest removing it

2022-04-11 07:37 UTC, bmx-makostecka commented on client/src/components/ArrayItems.tsx
> +          {state.showTruncatedList ? (
Now you duplicate a lot of code. I suggest changing it a little bit, something like that (I simplified it just for showing you what I mean 🙂 ):
`{props.data.length > 5 && (
    <div>
        <button onClick={toggleFullList}>
            {state.showTruncatedList ? 'Show' : 'Hide'} {props.data.length} items
        </button>
    </div>
)`
and of course, you need to change `hideFullList` and `showFullList` to `toggleFullList`

2022-04-11 09:26 UTC, bmx-makostecka commented on client/src/components/ArrayItems.tsx
> +          {state.showTruncatedList ? (
Justus, if you have any questions about what I wrote - ask me on slack 🙂

2022-04-11 09:50 UTC, bmxjusu commented on client/src/components/ArrayItems.tsx
> +          {state.showTruncatedList ? (
Good point! I changed it now :) Thank you for the feedback

2022-04-11 10:10 UTC, bmx-makostecka submitted a review, later dismissed

2022-04-11 11:52 UTC, bmxsele approved these changes

2022-04-11 11:53 UTC, bmxsele commented on client/src/components/ArrayItems.tsx
> +          {props.data.length > 5 && (
We can optionally create also a constant for this value `5` and call it for example: `TRUNCATED_LIST_SIZE` or something like that, but i think it's not required so i gave approval

2022-04-27 10:24 UTC, bmxsele approved these changes

2022-04-27 10:25 UTC, merged