Cm 541 Creating new permission tab
BerlingskeMedia/bpc_console pull request #219
Opened 2022-08-04 17:14 UTC by bmxarch

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/CM-541

### Before testing:

If it is not marged, you have to install dev version off one package.
https://github.com/BerlingskeMedia/bm.monorepo.ms-client-sdks/pull/40

```bash
npm install @berlingske-media/bm.node-module.newsletter-service-sdk@1.3.0-canary.40.184.0
# or 
yarn add @berlingske-media/bm.node-module.newsletter-service-sdk@1.3.0-canary.40.184.0
```

2022-08-08 18:52 UTC, bmxdaba requested changes

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +type HandleOnChange =
Rename to something more meaningful

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +const initState = {
use uppercase for constants like this one

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  type: 'SERVICE' | 'SALES' | 'PRODUCT' | 'NEWSLETTER' | 'default';
note:
extract it e.g.
```typescript
export type PermissionType = 'SERVICE' | 'SALES' | 'PRODUCT' | 'NEWSLETTER';
```
it would be best to provide this inside NSSdk itself

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  brandId: typeof BrandsId[keyof typeof BrandsId] | 'default';
use only `typeof BrandsId[keyof typeof BrandsId]`

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +};
```typescript
type FormValues = {
  name: string;
  hidden: boolean;
  frequency: string;
  description: string;
  consentText: string;
  type: PermissionType;
  brandId: typeof BrandsId[keyof typeof BrandsId];
};
```

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  }, [alert.status]);
```suggestion
  React.useEffect(() => {
    let timeoutId: NodeJS.Timeout | undefined;

    if (alert.status === 'success') {
      timeoutId = setTimeout(handleCancel, 2000);
    }

    return () => {
      if (timeoutId) {
        clearTimeout(timeoutId);
      }
    };
  }, [alert.status]);
```

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  const getFormValidation = () => {
simplify by returning false immediately when an invalidated field was wound
```typescript
const validateForm = (): boolean => {
  if (formValues.type === 'NEWSLETTER' && !formValues.frequency) {
    return false;
  }
  
  const formValueKeys = Object.keys(formValues);
  const requiredFormKeys = formValueKeys.filter(isRequriedField);
  
  for (const requiredKey of requiredFormKeys) {
    if (!formValues[requiredKey]) {
      return false;
    }
  }
  
  return true;
};
```

for this you can move outside the component:
```typescript
const isRequriedField = (field: keyof FormValues): boolean =>
  field !== 'frequency' && field !== 'hidden';
```

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  };
You can simplify it

```typescript
const createNewPermission = async (event: React.FormEvent): Promise<void> => {
  try {
    event.preventDefault();
    setIsPending(true);
  
    if (!validateForm()) {
      throw new Error('Fill form correctly!');
    }
  
    const newPermissionDto = createPermissionDto(formValues);
    await newsletterSdk.permissions.admin.create(newPermissionDto);
  
    setAlert({ status: 'success', msg: 'Created permission' });
  } catch (error) {
    setAlert({ status: 'error', msg: error.message });
  } finally {
    setIsPending(false);
  }
};
```

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  };
make it more readable by extracting long conditions to variables

```suggestion
 const handleFormElementChange = (event: React.ChangeEvent<FormElement>) => {
  const { value, name, type } = event.currentTarget as FormElement;
  const { checked } = event.currentTarget as HTMLInputElement;

  if (name === 'type' && value === 'newsletter') {
    return setFormValues((prevState: FormValues) => ({
      ...prevState,
      type: 'NEWSLETTER',
      frequency: '',
    }));
  }

  const newValue = type.toLowerCase() === 'checkbox' ? checked : value;

  setFormValues((prevState: FormValues) => ({
    ...prevState,
    [name]: newValue,
  }));
};
```

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +              Chose brand
`choose` :smile:

2022-08-08 18:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +              Chose type
same here :smiley:

2022-08-09 06:46 UTC, bmxkrbu requested changes

2022-08-09 06:46 UTC, bmxkrbu commented on client/src/Main.tsx
> +        <Route path="/newsletter" component={Newsletter} />
```suggestion
        <Route path="/newsletters" component={Newsletter} />
```

2022-08-09 06:48 UTC, bmxkrbu commented on client/src/components/FormField/Textarea.tsx
> +        value={currentValue || ''}
That's to protect from receiving an undefined value. Otherwise react will raise an issue.

2022-08-09 07:11 UTC, bmxkrbu requested changes

2022-08-09 07:11 UTC, bmxkrbu commented on client/src/newsletter/PermissionCreator.tsx
> +  brandId: typeof BrandsId[keyof typeof BrandsId] | 'default';
This seems super complicated anyways, see: https://github.com/BerlingskeMedia/bm.monorepo.ms-client-sdks/pull/40/files#r940976971

2022-08-09 07:23 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +        value={currentValue || ''}
that's what I meant :smile:
It would be more predictable if this fallback would be set inside `useState(value || '')` or as you said inside props destructing. Or even not allowing to pass any other values than a string to this component

2022-08-09 10:11 UTC, bmxkrbu requested changes

2022-08-09 10:11 UTC, bmxkrbu commented on client/src/newsletter/Newsletter.tsx
> +        </button>
This button should be added while developing this particular feature - it doesn't make sense to have a button which doesn't do anything.

2022-08-09 12:29 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +        value={currentValue || ''}
remove the fallback here due to `value = ''` in props destruction

2022-08-09 12:45 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +        window.history.back();
use `react-router-dom` https://v5.reactrouter.com/web/api/history object
When you use `window.history.back()` it changes the URL to the previous state, it may reloads all the resources
While operating on the `react-router-dom` allows to go though history that React will rerender only required component

2022-08-09 12:47 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  const createPermissionDto = (values: FormValues): CreatePermissionDto => {
move it outside the component, like `isRequiredField`

2022-08-09 12:52 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +    setAlert(initState.alert);
because we do not `debounce` the user input handling the whole form is quite expensive action itself
setting alert state to default value each time increases that cost a lot, what is not required. I suggest to add a small check here to set state to initial value only when 
```typescript
if (alert.status) {
   setAlert(INITIAL_STATE.alert)
}
```

2022-08-09 12:55 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +            onClick={() => window.history.back()}>
same here

2022-08-09 13:00 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +  const validateForm = (): boolean => {
note:
we can even go a bit further and extract this outside the component too.

P.S.
If I type `note` before - it is not something that you can add or leave as is in my opinion :smiley: 

```typescript
const validateForm = (values: FormValues): boolean => {
  if (values.type === 'NEWSLETTER' && !values.frequency) {
    return false;
  }

  const formValueKeys = Object.keys(values);
  const requiredFormKeys = formValueKeys.filter(isRequiredField);

  for (const requiredKey of requiredFormKeys) {
    if (!formValues[requiredKey]) {
      return false;
    }
  }

  return true;
};

// then..

if (!validateForm(formValues)) {
   throw new Error() //...
}
```

2022-08-09 13:03 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
>        brandId: parseInt(values.brandId.toString(), 10),
because we have simplified the `FormValues` type for `brandId` field then this parsing is not required; types are matching now to `CreatePermissionDto`

2022-08-09 13:03 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
> +            onClick={() => window.history.back()}>
same here

2022-08-09 13:12 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +      {label && <label htmlFor={id || name}>{label}</label>}
`for` in labels has to be equal to `id` of form field element
```suggestion
      {label && <label htmlFor={id}>{label}</label>}
```

2022-08-09 13:13 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +        aria-describedby={`help-${id || name}`}
cause it's already extracted you can use it here

2022-08-09 13:22 UTC, bmxkrbu commented on client/src/newsletter/PermissionCreator.tsx
> +const initState = {
nah, we've never used upper case for constants

2022-08-09 13:24 UTC, bmxkrbu requested changes

2022-08-09 13:24 UTC, bmxkrbu commented on client/src/newsletter/PermissionCreator.tsx
> +      setAlert({ status: 'success', msg: 'Created permission' });
```suggestion
      setAlert({ status: 'success', msg: 'Permission created' });
```

2022-08-09 14:12 UTC, bmxarch commented on client/src/newsletter/PermissionCreator.tsx
>        brandId: parseInt(values.brandId.toString(), 10),
Parsing is still required because returned value of select input is a string.

2022-08-09 20:35 UTC, bmxdaba commented on .babelrc
> -    "@babel/preset-typescript"
why did you remove this preset?

2022-08-09 20:35 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
>        brandId: parseInt(values.brandId.toString(), 10),
Yeah, my bad. But the types are wrong anyway then :smiley: 
to change:
```typescript
type FormValues = {
  name: string;
  hidden: boolean;
  frequency: string;
  description: string;
  consentText: string;
  type: PermissionType;
  brandId: string; // here
};

const createPermissionDto = (values: FormValues): CreatePermissionDto => {
  return {
    ...values,
    brandId: parseInt(values.brandId), // then this
    enabled: true,
    sortId: 0,
  };
};

const INITIAL_STATE = {
  values: {
    name: '',
    frequency: '',
    brandId: BrandIds.BER.toString(), // and this
    type: 'SERVICE',
    hidden: false,
    description: '',
    consentText: '',
  },
  alert: {
    status: null,
    msg: '',
  },
} as InitialState;
```

2022-08-10 08:05 UTC, bmxarch commented on .babelrc
> -    "@babel/preset-typescript"
I should delete only @babel/preset-typescript. Using enums like consts generated bugs so i added ts-loader to webpack config and Krzysiek said, that typescript preset is not necessary in babel config. 
I will return preset-react back in next fix.

2022-08-10 08:05 UTC, bmxarch commented on .babelrc
> -    "@babel/preset-typescript"
I should delete only @babel/preset-typescript. Using enums like consts generated bugs so i added ts-loader to webpack config and Krzysiek said, that typescript preset is not necessary in babel config. 
I will return preset-react back in next fix.

2022-08-10 11:43 UTC, bmxdaba requested changes

2022-08-10 11:43 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +        value={currentValue || ''}
remove the fallback here due to value = '' in props destruction

2022-08-10 11:52 UTC, bmxdaba requested changes

2022-08-10 11:52 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +      {label && <label htmlFor={id || name}>{label}</label>}
```typescript
let Label = null;

if (label) {
   label = ? <label htmlFor={id}>{label}</label> : <label>{label}</label>;
}

// then

{Label}
```

2022-08-10 13:15 UTC, bmxdaba commented on client/src/components/FormField/Textarea.tsx
> +        value={currentValue || ''}
```suggestion
        value={currentValue}
```

2022-08-10 14:08 UTC, bmxdaba submitted a review, later dismissed

2022-08-16 08:31 UTC, bmxdaba approved these changes

2022-08-16 08:58 UTC, merged