BMD-12345 Added label for deleted accounts.
BerlingskeMedia/bpc_console pull request #221
Opened 2022-08-09 13:28 UTC by bmxarch

Added label to indicate an acc is deleted and blocked update button if user is marked as deleted

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-12345

2022-08-09 13:29 UTC, bmxkrbu submitted a review, later dismissed

2022-08-10 12:04 UTC, bmxdaba requested changes

2022-08-10 12:04 UTC, bmxdaba commented on client/src/clients/EditClientForm.tsx
> +            disabled={pending || !!props.isDeleted}>
there is no need to cast `isDeleted` to boolean since it is already a boolean

2022-08-10 12:21 UTC, bmxarch commented on client/src/clients/EditClientForm.tsx
> +            disabled={pending || !!props.isDeleted}>
I was getting an error that props.isDeleted may be null.

2022-08-10 12:34 UTC, bmxdaba commented on client/src/clients/EditClientForm.tsx
> +            disabled={pending || !!props.isDeleted}>
oh, I see `Partial<Nullable<{]>`

2022-08-10 12:34 UTC, bmxdaba approved these changes

2022-08-11 12:51 UTC, merged