Cm 621 - Creating new permission 2.0 (improvements)
BerlingskeMedia/bpc_console pull request #228
Opened 2022-08-22 10:43 UTC by bmxarch

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/CM-621

2022-08-23 07:07 UTC, bmxdaba requested changes

2022-08-23 07:07 UTC, bmxdaba commented on client/src/newsletter/PermissionCreator.tsx
>        }
invert to make it more readable

```suggestion
      if (!isValid) {
         setFormErrors((formErrors) => ({
          ...formErrors,
          ...newErrorState,
        }));
        throw new Error('validation');
      }
      
       const newPermissionDto = createPermissionDto(formValues);
       await newsletterSdk.permissions.admin.create(newPermissionDto); 
```

2022-08-24 09:33 UTC, bmxarch commented on client/src/components/FormField/Textbox.tsx
>          id={id || name}
This change messes up a lot of tests and that's the reason I changed it that way. It happens because many textboxes don't have passed id (only name) but have label. 
Tests look for input by label so when there is no id cypress throws errors. 

We should require an id if a label is passed and fix all Textboxes or leave it as it is above.

2022-08-25 01:20 UTC, bmxdaba approved these changes

2022-08-25 08:00 UTC, merged