BMD-13478 Browsing existing permissions
BerlingskeMedia/bpc_console pull request #229
Opened 2022-08-24 09:13 UTC by bmxarch

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-13478

For now to testing is required to change env NS_URL to qa2 and install testing ver of NSSDK

`NS_URL=https://api-qa2.newsletter.idm.aws.berlingskemedia-testing.net`

2022-09-02 07:16 UTC, bmxdaba requested changes

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/PermissionsFilter.tsx
> +  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
each `if` should have a `return` inside

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Permission.tsx
> +const getShortDescription = (description = '') =>
use `text-overflow: ellipsis` instead

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +      {!state.isProcessing && !state.permissions.length && 'no records'}
join conditions

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +    }
```typescript
   setState((state) => ({
        ...state,
        permissions,
        size,
        filterParams,
    }));
    } catch (e) {
      console.error(e.errorCode);
    } finally {
      setState((state) => ({
          ...state,
          isProcessing: false,
      }));
}
```

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +        search || undefined,
just search

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +        disabled ? undefined : !disabled,
unreadable

2022-09-02 07:16 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +        );
as above

2022-09-02 09:17 UTC, bmxarch commented on client/src/newsletter/Newsletter.tsx
> +        hidden && undefined,
it's false or undefined but it's correct. 

**respond:** 
`if false -> only visible permissions ` (default) 
`if true -> only disabled permissions ` (we don't use it here) 
`undefined -> everything` (checkbox show hidden checked)

2022-09-02 09:24 UTC, bmxarch commented on client/src/newsletter/Newsletter.tsx
> +        disabled ? undefined : !disabled,
`!disabled || undefined` 
it could be better

2022-09-02 09:24 UTC, bmxarch commented on client/src/newsletter/Newsletter.tsx
> +        );
`!disabled || undefined` 
it could be better

2022-09-05 07:14 UTC, bmxdaba requested changes

2022-09-05 07:14 UTC, bmxdaba commented on client/src/newsletter/permission.module.scss
> +  width: 25vw;
I am not quite sure if we would like to operate on device width in such a case :thinking:

2022-09-05 07:14 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +        search || undefined,
you can send an empty string
```typescript
        ...(name?.length > 0 ? { name: { contains: name, mode: 'insensitive' } } : {}),
```

2022-09-05 07:23 UTC, bmxdaba requested changes

2022-09-05 07:23 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +        !disabled || undefined,
extract as 

```typescript
const showEnabled = !disabled || undefined;
```

2022-09-05 09:05 UTC, bmxdaba approved these changes

2022-09-08 12:17 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
```typescript
const { headers, body: permissions } = await newsletterSdk.permissions.admin.getMany(
```
be aware that `size` and `page` headers are always passed so there is no need to make a fallback 
```typescript
const size = parseInt(headers.get('size'), 10);
```

2022-09-08 12:59 UTC, bmxarch commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
The `get` method from `headers` has it set that the return value is string | null, so we have to keep the fallback. 

Body it is a Promise, so we can't pass it directly to the state after destructering. 

It will be works
```js
const { headers, body } = await newsletterSdk.permissions.admin.getMany(

const size = parseInt(headers.get('size') || '0', 10);
const permissions = await body;
```

2022-09-08 13:45 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
Yeah, I forgot about headers. Speaking of destructing the promise, why not? It should work. Simple test in a browser console:
![image](https://user-images.githubusercontent.com/105216028/189138279-553fafdb-ccdd-4f70-96e8-aeb0516a9d09.png)

2022-09-08 14:12 UTC, bmxarch commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
![Screenshot from 2022-09-08 16-11-55](https://user-images.githubusercontent.com/109528139/189144712-1d22d05f-ec84-4150-b24e-12dca073f73d.png)

2022-09-09 06:13 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
oh, so yeah - that's the problem :smiley: 
https://github.com/BerlingskeMedia/bm.monorepo.ms-client-sdks/blob/3674d6988d298e14863714ac1c911d2705c1102c/packages/bm.node-module.newsletter-service-sdk/src/modules/permissions-admin-module.ts#L74

change there to 
```typescript
{
   headers: response.headers,
   body: await response.json(),
}
```

2022-09-09 06:14 UTC, bmxdaba commented on client/src/newsletter/Newsletter.tsx
> +      const NSSDKRespond = await newsletterSdk.permissions.admin.getMany(
haven't thought of that while reviewing those changes

2022-09-09 08:18 UTC, bmxdaba approved these changes

2022-09-09 09:11 UTC, bmxdaba approved these changes

2022-09-13 06:37 UTC, merged