BMD-13509
BerlingskeMedia/bpc_console pull request #237
Opened 2022-09-05 09:39 UTC by bmxarch

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-13509

2022-09-05 13:29 UTC, bmxdaba requested changes

2022-09-05 13:29 UTC, bmxdaba commented on client/src/Main.tsx
> +          path="/newsletters/edit-permission"
you cannot open a specifc newsletter using URL only. Change to `/newsletters/permission/:id`

2022-09-05 13:29 UTC, bmxdaba commented on client/src/components/FormField/Select.tsx
> +        value={currentValue || ''}
I would move it here
```typescript
  const [currentValue, setCurrentValue] = React.useState(selectProps.value || '');
```

2022-09-05 13:29 UTC, bmxdaba commented on client/src/newsletter/Permission.tsx
> +  const permissionInfo = {
note: extract a function to map the value; just for readability

2022-09-06 07:07 UTC, bmxdaba requested changes

2022-09-06 07:07 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +      }
```typescript
// outside the component
const mapPermissionToFormValues = (permission: Permission): FormValues => ({
   // map values
});

//then.. 
      try {
        setIsPending(true);
        const permission = await newsletterSdk.permissions.admin.get(id);
        setPermissionData(mapPermissionToFormValues(permission));
      } catch (error) {
        setAlert('The permission with the given id does not exist!');
        console.error(error);
      } finally {
        setIsPending(false);
      }
```

2022-09-06 07:07 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +  const [permissionData, setPermissionData] = React.useState<FormValues | null>(
I would rename it to `const [formValues, setFormValues]`

2022-09-06 07:13 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +      }
and here `setAlert('The permission with the given id does not exist!');` should only be displayed for `404` statusCode

so it should be like this:

```typescript
catch (error) {
   const errorMessage = error.statusCode === 404
             ? 'The permission with the given id does not exist!'
             : error.message;
   setAlert(errorMessage);
   console.error(error);
}
```

2022-09-06 09:28 UTC, bmxarch commented on client/src/newsletter/PermissionEditor.tsx
> +  const [permissionData, setPermissionData] = React.useState<FormValues | null>(
I think `[initFormValues, setInitFormValues]` will be best option.

This fragment is more readable in my opinion
```
const [initFormValues, setInitFormValues]
...
...
 const updatePermission = async (formValues: FormValues): Promise<void> => {
    if (!initFormValues) return;
    try {
      setIsPending(true);
      if (!checkChanges(formValues, initFormValues)) {
        setAlert('No changes was provided!');
        throw new Error('validation');
      }
```

2022-09-07 06:54 UTC, bmxdaba requested changes

2022-09-07 06:54 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +      {!initFormValues && alert && <PermissionNotFound alertMsg={alert} />}
note: 
```suggestion
      {initFormValues ? (
        <PermissionForm
          submitButtonDisplayValue="Save"
          initFormValues={initFormValues}
          alert={alert}
          isProcessing={isPending}
          requiredFields={requiredFields}
          disabledElements={disabledElements}
          handleCancel={() => handleSwitchRoute('cancel')}
          onSubmit={updatePermission}
          handleResetAlert={handleResetAlert}
        />
      ) : alert ? (
        <PermissionNotFound alertMsg={alert} />
      ) : null}
```

2022-09-07 06:54 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +  const [permissionData, setPermissionData] = React.useState<FormValues | null>(
but they aren't init form values, just a form values :thinking:

2022-09-12 07:01 UTC, bmxdaba approved these changes

2022-09-12 07:42 UTC, bmxdaba commented on client/src/newsletter/PermissionEditor.tsx
> +const hasFormValuesChanged = (
`have`; my bad :sweat_smile:

2022-09-14 10:17 UTC, bmxpiku approved these changes

2022-09-19 07:53 UTC, bmxpiku approved these changes

2022-09-19 07:55 UTC, merged