CM-754 File Import - Batch Subscribe/Unsubscribe users via CSV (websocket)
BerlingskeMedia/bpc_console pull request #244
Opened 2022-09-20 13:07 UTC by bmxarch

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/CM-754
https://berlingskemedia.atlassian.net/browse/CM-800

2022-10-10 06:47 UTC, bmxdaba requested changes

2022-10-10 06:47 UTC, bmxdaba commented on client/src/components/FormField/FileUpload.tsx
> +    }
```suggestion
    if (inputRef.current) {
      const { files = [] } = inputRef.current;
      const name = files.length ? files[0].name : '';
      setFileName(name);
    }
```

2022-10-10 06:47 UTC, bmxdaba commented on client/src/newsletter/forms/SignupsUpdateForm.tsx
> +};
```typescript
const disableSubmit = (
  { permissionId, campaignId, confirm, file }: FormValues,
  error: string | null,
): boolean => {
  if (error) {
    return true;
  }  
  
  const areRequiredValuesFilled = permissionId && campaignId && confirm && file.filePath;
  return !areRequiredValuesFilled;
};
```

2022-10-10 06:47 UTC, bmxdaba commented on client/src/newsletter/helpers/usePermissionInfo.ts
> +    });
invert conditions

```typescript
if (!debounce) {
   return setPermissionInfo({
    name: null,
    description: null,
    errorMsg: 'Unknown permission',
  });
}

(async () => {
    try {
      const permission = await newsletterSdk.permissions.admin.get(
        debounce,
      );

      if (!permission?.name) {
         throw new Error('Unknown permission');
      }

      setPermissionInfo({
          name: permission.name,
          description: `Description: ${permission.description}`,
          errorMsg: null,
        });

    } catch (error) {
      setPermissionInfo({
        name: null,
        description: null,
        errorMsg: error,
      });
    }
})();
```

2022-10-10 10:37 UTC, bmxarch commented on client/src/Main.tsx
> +        <Route exact path="/clients" component={Clients} />
I had to test something on this branch which concerned another task and this change got lost. Anyway deleted.

2022-10-10 10:45 UTC, bmxarch commented on client/src/components/FormField/FileUpload.tsx
> +    }
still ts type error so
```suggestion
    if (inputRef.current) {
      const { files = [] } = inputRef.current;
      const name = files && files.length ? files[0].name : '';
      setFileName(name);
    }
```

2022-10-10 10:53 UTC, bmxarch commented on client/src/newsletter/forms/SignupsUpdateForm.tsx
> +};
```suggestion
const disableSubmit = (
  { permissionId, campaignId, confirm, file }: FormValues,
  error: string | null,
): boolean => {
  if (error) return true;

  const areRequiredValuesFilled = !!(
    permissionId &&
    campaignId &&
    confirm &&
    file.filePath
  );
  return !areRequiredValuesFilled;
};
```

2022-10-10 10:55 UTC, bmxdaba commented on client/src/newsletter/forms/SignupsUpdateForm.tsx
> +};
why cast `!!` if it's already a boolean due to `&&`
```typescript
!!(
    permissionId &&
    campaignId &&
    confirm &&
    file.filePath
  );
```

2022-10-10 13:56 UTC, bmxdaba requested changes

2022-10-10 13:56 UTC, bmxdaba commented on client/src/newsletter/singups/SignupsUpdate.tsx
> +      history.replace(`/newsletters/signups-update/${type}`);
why not one?

2022-10-11 06:44 UTC, bmxarch commented on client/src/newsletter/singups/SignupsUpdate.tsx
> +      history.replace(`/newsletters/signups-update/${type}`);
Because if we use only last history replace component will not re-render so in this case nothing happens.
That's why first I go to singups-update and next to singups-update/$type. 
Component state back to init and connection ws is restarted.

2022-10-11 09:16 UTC, bmxdaba commented on client/src/newsletter/singups/SignupsUpdate.tsx
> +      history.replace(`/newsletters/signups-update/${type}`);
I get what you want to do. Just call `setState(INIT_STATE)` instead -> changing state rerenders the component

2022-10-11 11:01 UTC, bmxdaba commented on client/src/newsletter/singups/SignupsUpdate.tsx
> +      history.replace(`/newsletters/signups-update/${type}`);
just to confirm. Did you want to re-render the component or initiate the WS connection? If the WS - then you should re-trigger useListeners using its dependencies

2022-10-11 11:04 UTC, bmxdaba approved these changes

2022-10-18 11:55 UTC, bmxkrze approved these changes

2022-10-18 12:02 UTC, merged