Bmd 10360
BerlingskeMedia/bpc_console pull request #83
Opened 2021-09-21 10:00 UTC by bmxkrbu

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/BMD-10360

### Pre/Post release actions:
(none)

2021-09-22 10:38 UTC, bmx-makostecka requested changes

2021-09-22 10:38 UTC, bmx-makostecka commented on .vscode/settings.json
> +}
```suggestion
}

```

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/companies/Companies.tsx
> +function getUrlParameter(name: string) {
you have this function duplicated in client/src/companies/CompanySearch.tsx

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/companies/CompanySearch.tsx
> +    setState((state: any) => ({ ...state, searchInProgress: true }));
```suggestion
    setState((state: CompanySearchState) => ({ ...state, searchInProgress: true }));
```

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/companies/CompanySearch.tsx
> +      // userSearchBoxClass += ' has-error'
shouldn't these comments be removed?

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/components/ArrayItems.tsx
> +            {/* <div className="form-group has-feedback"> */}
remove this comment

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/companies/company/Company.tsx
> +export class Company extends React.Component<CompanyProps, CompanyState> {
Weren't we supposed to change classes to function components?

2021-09-22 10:38 UTC, bmx-makostecka commented on client/src/companies/planInstances/AddPlaninstancesUser.tsx
> +  // this.addUser = this.addUser.bind(this);
remove comments

2021-09-22 11:01 UTC, bmxkrbu commented on client/src/companies/Companies.tsx
> +function getUrlParameter(name: string) {
I didn't want to change it in this task

2021-09-23 08:41 UTC, bmxsele requested changes

2021-09-23 08:41 UTC, bmxsele commented on .vscode/settings.json
> +{
I have mixed feelings about adding IDE settings to the repository :thinking: I would preffer to remove that and add .vscode to .gitignore

2021-09-23 12:04 UTC, bmxkrbu commented on client/src/companies/company/Company.tsx
> +export class Company extends React.Component<CompanyProps, CompanyState> {
The scope of the task was to break down into individual files :)

2021-09-23 12:06 UTC, bmxkrbu commented on .vscode/settings.json
> +{
Me too...
VScode by default uses a built-in typescript version which might be different than the one we use in the project. This can cause discrepancies if devs are not on the same version.

2021-09-23 12:10 UTC, bmxkrbu commented on client/src/companies/CompanySearch.tsx
> +      // userSearchBoxClass += ' has-error'
Perhaps, but that's existing

2021-09-23 12:10 UTC, bmxkrbu commented on client/src/components/ArrayItems.tsx
> +            {/* <div className="form-group has-feedback"> */}
That's also existing

2021-09-23 12:26 UTC, bmxsele approved these changes

2021-09-23 12:27 UTC, bmx-makostecka approved these changes

2021-09-23 12:31 UTC, merged